[package]
name = "easy_prefs"
version = "0.1.0"
edition = "2021"
authors = ["Tyler Patterson <tyler@everaccountable.com>"]
description = "A simple, safe, and performant preferences library by Ever Accountable."
license = "MIT OR Apache-2.0"
homepage = "https://everaccountable.com"
repository = "https://github.com/yourusername/easy_prefs"
documentation = "https://docs.rs/easy_prefs"

[dependencies]
paste = "1.0.15"
toml = "0.8.20"
serde = { version = "1.0.218", features = ["derive"] }
directories = "6.0.0"
tempfile = "3.17.1"  # Used to tell us where we can store the user's data on different platforms

